#!/bin/bash

exec 1> >(logger -s -t $(basename $0)) 2>&1

apt-get update &&
apt-get dist-upgrade -y &&
apt-get clean &&
apt-get autoremove -y &&
#only if python packages needed
#pip list --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1 | xargs -n1 pip install -U
